export const SET_COMMON_STORE = 'SET_COMMON_STORE';
export const SET_SIMBOX_CONNECTION_ALIVE = 'SET_SIMBOX_CONNECTION_ALIVE';
export const SET_PARTIAL_COMMON_STORE_UPDATE = 'SET_PARTIAL_COMMON_STORE_UPDATE';
